[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
dotenv = "0.15.0"
postgrest = "1.6.0"
go_true = "0.1.1"
tokio = { version = "1.42.0", features = ["full"] }
clap-cargo = "0.14.1"
